name: WP Packages Changelog

on:
  pull_request:
    paths:
      - 'composer.lock'

jobs:
  changelog:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Comment changelogs on PR
        uses: roots/wp-packages-changelog-action@v3
